services:
  postgres:
    image: postgres:16-alpine
    container_name: roomio-postgres
    environment:
      POSTGRES_USER: roomio
      POSTGRES_PASSWORD: roomio
      POSTGRES_DB: roomio
    ports:
      - "5432:5432"
    volumes:
      - roomio_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: roomio-redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - roomio_redis_data:/data

volumes:
  roomio_pg_data:
  roomio_redis_data:
