import type { CSSProperties } from 'react';

/** Roomio design tokens — tek kaynak (B · Slate + Teal) */
export const roomioTheme = {
  sidebar: '#252b3b',
  sidebarHover: 'rgba(255, 255, 255, 0.06)',
  sidebarActive: '#2563eb',
  sidebarActiveLeaf: 'rgba(37, 99, 235, 0.28)',
  sidebarText: '#e2e8f0',
  sidebarMuted: 'rgba(255, 255, 255, 0.42)',
  accent: '#14b8a6',
  accentSoft: '#ccfbf1',
  accentDark: '#0d9488',
  brandBlue: '#2563eb',
  header: '#ffffff',
  surface: '#eef2f6',
  surfaceAlt: '#e8edf3',
  card: '#ffffff',
  border: '#e2e8f0',
  borderStrong: '#cbd5e1',
  text: '#0f172a',
  textMuted: '#64748b',
  success: '#059669',
  warning: '#d97706',
  danger: '#dc2626',
  radiusSm: '8px',
  radiusMd: '12px',
  radiusLg: '16px',
  radiusXl: '20px',
  shadowSm: '0 1px 2px rgba(15, 23, 42, 0.05)',
  shadowMd: '0 4px 16px rgba(15, 23, 42, 0.07)',
  shadowLg: '0 12px 32px rgba(15, 23, 42, 0.1)',
} as const;

export const cssVars: CSSProperties = {
  ['--roomio-sidebar' as string]: roomioTheme.sidebar,
  ['--roomio-sidebar-hover' as string]: roomioTheme.sidebarHover,
  ['--roomio-sidebar-active' as string]: roomioTheme.sidebarActive,
  ['--roomio-sidebar-active-leaf' as string]: roomioTheme.sidebarActiveLeaf,
  ['--roomio-sidebar-text' as string]: roomioTheme.sidebarText,
  ['--roomio-sidebar-muted' as string]: roomioTheme.sidebarMuted,
  ['--roomio-accent' as string]: roomioTheme.accent,
  ['--roomio-accent-soft' as string]: roomioTheme.accentSoft,
  ['--roomio-accent-dark' as string]: roomioTheme.accentDark,
  ['--roomio-brand-blue' as string]: roomioTheme.brandBlue,
  ['--roomio-header' as string]: roomioTheme.header,
  ['--roomio-surface' as string]: roomioTheme.surface,
  ['--roomio-surface-alt' as string]: roomioTheme.surfaceAlt,
  ['--roomio-card' as string]: roomioTheme.card,
  ['--roomio-border' as string]: roomioTheme.border,
  ['--roomio-border-strong' as string]: roomioTheme.borderStrong,
  ['--roomio-text' as string]: roomioTheme.text,
  ['--roomio-text-muted' as string]: roomioTheme.textMuted,
  ['--roomio-radius-sm' as string]: roomioTheme.radiusSm,
  ['--roomio-radius-md' as string]: roomioTheme.radiusMd,
  ['--roomio-radius-lg' as string]: roomioTheme.radiusLg,
  ['--roomio-radius-xl' as string]: roomioTheme.radiusXl,
  ['--roomio-shadow-sm' as string]: roomioTheme.shadowSm,
  ['--roomio-shadow-md' as string]: roomioTheme.shadowMd,
  ['--roomio-shadow-lg' as string]: roomioTheme.shadowLg,
};
